# Generated by Django 3.2.5 on 2021-07-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='detail',
            field=models.CharField(default='Provide meeting details...', max_length=100),
        ),
    ]
